apiVersion: datamover.a-cup-of.coffee/v1alpha1
kind: DataMoverSchedule
metadata:
  labels:
    app.kubernetes.io/name: datamover-operator
    app.kubernetes.io/managed-by: kustomize
  name: datamovercron-sample
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  sourcePvc: cephfs-pvc
  secretName: example-bucket
  addTimestampPrefix: true
  deletePvcAfterBackup: true
  suspend: false
  image:
    repository: ttl.sh/rclone_op
    tag: latest
  additionalEnv:
    - name: "TLS_HOST"
      value: "false"
    - name: "BUCKET_HOST"
      valueFrom:
        configMapKeyRef:
          name: example-bucket
          key: BUCKET_HOST
    - name: "BUCKET_PORT"
      valueFrom:
        configMapKeyRef:
          name: example-bucket
          key: BUCKET_PORT
    - name: "BUCKET_NAME"
      valueFrom:
        configMapKeyRef:
          name: example-bucket
          key: BUCKET_NAME