---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datamover.a-cup-of.coffee
  resources:
  - datamoverpopulators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamover.a-cup-of.coffee
  resources:
  - datamovers
  - datamoverschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datamover.a-cup-of.coffee
  resources:
  - datamoverschedules/finalizers
  verbs:
  - update
- apiGroups:
  - datamover.a-cup-of.coffee
  resources:
  - datamoverschedules/status
  verbs:
  - get
  - patch
  - update
